print("Please Enter Your Name")
name=input()
print("Your name is "   +name)
print(type(name))
print("please Enter your age ")
age=input()
print("your age is " +age)
print(type(age))
print("please Enter your Mobile number ")
number=input()
print("your number is " +number)
print(type(number))
print("please Enter your gender")
gender=input()
print("your are " +gender)
print(type(gender))
print("please Enter your address")
address=input()
print("your address is " +address)
print(type(address))